### ISSUE TITLE
streaming api

### ISSUE THREAD

**Issue by mariusradvan** [jdub/node-twitter#19]
for how long will a connection remain open for streaming api? i want to keep it open as long as the script runs (days/months etc)

**Comment by AvianFlu** [comment]
Until a network error occurs, you get rate limited, or your computer explodes.  So, pretty much as long as your script is running.

**Comment by mariusradvan** [comment]
AvianFlu - I filter those tweets with some keywords. So I get at most 60 tweets/minute, but sometimes even one tweet in two minutes. But does the connection ever closes? By twitter, maybe, after a while? I want to know how to find that out, with this module, and automatically reopen it.
