### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by cheeyeo** [jdub/node-twitter#23]
When using the node-twitter library in a recent project it failed overnight with the following error:

Error: ECONNREFUSED, Connection refused
    at Client._onConnect (net.js:601:18)
    at IOWatcher.onWritable [as callback](net.js:186:12)

Has the api for twitter changed?

**Comment by christopherwright** [comment]
Twitter changed, see: https://dev.twitter.com/blog/streaming-api-turning-ssl-only-september-29th

If you just want to manually fix this to get your project running again, then try this: https://github.com/christopherwright/node-twitter/commit/01c2569157d99b362ffc8bbea77b4bbda9c62932

**Comment by jdub** [comment]
Fixed (by christopherwright!) in v0.1.18. Thanks! :-)
