### ISSUE TITLE
High CPU

### ISSUE THREAD

**Issue by NHQ** [jdub/node-twitter#27]
Does anybody else experience high CPU b/c of this module? I go from 0 to 90% in about 15 minutes. Haven't done any hardcore heap analysis yet, cuz I sort of don't know how yet.

Has any one tested it in node 0.5.10 yet?

**Comment by AvianFlu** [comment]
What kind of tracking terms are you using?  I'd imagine that a stream with lots and lots of tweets could peg a CPU.  

I'll do some 0.5.x testing this weekend, we'll see what happens.

**Comment by NHQ** [comment]
I'm eating a 200+ tag stream. My linode stats say that max incoming data rate has been 200 kb/s, average 30 kb/s including off-time. Maybe 3 updates per second. No crashes, even over 12+hours running, just high CPU. I too will run some tests in 0.5.10, which holds unspoken promises.

**Comment by NHQ** [comment]
This was a user error!
