### ISSUE TITLE
keygrip v2.1 breaks node-twitter due to existsSync fix

### ISSUE THREAD

**Issue by dworrad** [jdub/node-twitter#30]
Error:

defaults = fs.existsSync( keysPath )
TypeError: Object #<Object> has no method 'existsSync'

**Comment by jdub** [comment]
I can't replicate this -- has this already been fixed in keygrip? If you're still seeing it, please provide the code which causes the error. Thanks.

**Comment by ribeirobreno** [comment]
Verify the nodejs version. In linux, the command is `node --version`.

See [the changes between v0.6 and v0.8](https://github.com/joyent/node/wiki/API-changes-between-v0.6-and-v0.8).

**Comment by dworrad** [comment]
Heroku... v0.6.x

line 7 here https://github.com/jed/keygrip/commit/11ecc5d2b217bab036642b032107b9de3dd64db6 was the line throwing the error.

**Comment by dworrad** [comment]
After reading the changes... I guess v0.6.x is an issue
