### ISSUE TITLE
API Rate limit message breaking stream parser

### ISSUE THREAD

**Issue by Incisive** [jdub/node-twitter#33]
I'm noticing an issue when you reach the API rate limiter when creating streams in this bit of code (parser.js):

``` javascript
  // We have END?
  while ((index = this.buffer.indexOf(Parser.END)) > -1) {
    json = this.buffer.slice(0, index);
    this.buffer = this.buffer.slice(index + Parser.END_LENGTH);
    if (json.length > 0) {
      try {
        json = JSON.parse(json);
        this.emit('data', json);
      } catch (error) {
        this.emit('error', error);
      }
    }
  }
```

It appears that the JSON.parse is attempting to parse the error message returned by twitter, which is not JSON:

```
"Easy there, Turbo. Too many requests recently. Enhance your calm."
```

This took a bit of time to track down as the error appearing in the console was:

```
[SyntaxError: Unexpected token E]
```

**Comment by Under-Warz** [comment]
+1 Yes ! We need to listen a event type "limit" or "rate" to catch this data :)
