### ISSUE TITLE
Update to Twitter API 1.1

### ISSUE THREAD

**Issue by travis154** [jdub/node-twitter#34]
API 1 is now deprecated and will be removed on March 2013.

**Comment by deckchairhq** [comment]
Blackout tests of the API v1 are now commencing and the retirement has been moved back to June 11 2013.
https://dev.twitter.com/blog/api-v1-retirement-final-dates

**Comment by gotjosh** [comment]
Think it's time to review this again?

**Comment by desmondmorris** [comment]
This has been merged - https://github.com/jdub/node-twitter/pull/35

The module is now being tracked here: https://github.com/desmondmorris/node-twitter
