### ISSUE TITLE
Favorite a tweet

### ISSUE THREAD

**Issue by frevanauseloos** [jdub/node-twitter#43]
I would like to favorite a tweet with the id. Is this possible? Could you give me an example?
Thanks!

**Comment by desmondmorris** [comment]
I have added an examples file here - https://github.com/desmondmorris/node-twitter/blob/master/examples/favorites.js.  Hope that helps

Also, this module is now maintained here: http://github.com/desmondmorris/node-twitter

**Comment by frevanauseloos** [comment]
I'm still getting the same error: 404 page not found.
Any ideas? Thanks for the example, getFavorites works great!

```
twit.search('#test123454321', function(data) {
    data.statuses.forEach(function(tweet){
        logger.info(tweet.id);
        twit.createFavorite({id: tweet.id}, function(res){
            console.log(res);
        });
    });
});

{ [Error: HTTP Error 404: Not Found]
  statusCode: 404,
  data: '{"errors":[{"message":"Sorry, that page does not exist","code":34}]}' }
```

**Comment by desmondmorris** [comment]
Can you give the createFavorite method a shot with a few other tweets?  I am able to favorite a few different tweets in my timetime, but it fails on the two tweets that come up in that search.  This may or may not be related to https://twittercommunity.com/t/post-favorites-create-giving-error-while-using-rest-api-version-1-1/10807

**Comment by desmondmorris** [comment]
OK - Figured it out.  You need to use the `id_str` property instead of `id`

so `tweet.id` becomes `tweet.id_str`

**Comment by frevanauseloos** [comment]
Nice! Thanks
