### ISSUE TITLE
node-twitter is using a deprecated cookie library

### ISSUE THREAD

**Issue by christopherdbull** [jdub/node-twitter#8]
When running a script using twitter, npm throws this error: This library has been deprecated. Please use `npm install cookies` instead.

I'm guessing this means the lib needs to be rewritten to use the newer cookie lib.  I would offer to do it, but I'm a bit of a beginner at node.js as it is!

**Comment by jdub** [comment]
Yep, this transition only just happened. That's just a warning (not an error), and it still works fine. Note that the cookie stuff only matters if you're using the built-in Twitter authorisation and gatekeeper functionality (for your web front end). Will update to the new package soon.

**Comment by christopherdbull** [comment]
Ahh! That makes sense.  Thanks for replying so quickly

**Comment by christopherdbull** [comment]
for some reason it reopened, just closing again..

**Comment by jdub** [comment]
I re-opened it because the bug isn't fixed. :-)

**Comment by oesmith** [comment]
FYI, using cookie breaks express.js (I'm using express 2.3.2 on node.js 0.4.6) -- I'm guessing it's the monkey-patching on http.writeHead that's screwing something up..

ETA: when I say it breaks express.js, I mean it breaks HTTP headers in express -- everything works fine, just no headers get set. ever.

**Comment by jdub** [comment]
Thanks for the report... I need to transition from the 'cookie' module to its replacement, 'cookies' anyway, so it'll be a good excuse to ditch the auth handling stuff from the main node-twitter module entirely. It really ought to be separate.

**Comment by oesmith** [comment]
Just for a quick fix to this, I've migrated the existing code straight to cookies (it was actually pretty much a drop-in replacement).

I'll open a pull request...

**Comment by jdub** [comment]
Fixed by oesmith in v0.1.18. Thanks! :-)
